from app.models.role import Role
from app.models.user import User
from app.models.audit_log import AuditLog
from app.models.department import Department
from app.models.student import Student
from app.models.lecturer import Lecturer
from app.models.department_staff import DepartmentStaff
from app.models.course import Course
from app.models.course_material import CourseMaterial
from app.models.course_batch import CourseBatch
from app.models.course_application import CourseApplication
from app.models.batch_enrollment import BatchEnrollment